name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ["self-hosted" , "Linux"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install AWS CLI
      run: |
        ls -lrt
