name: Docker Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Determine version
      id: version
      run: echo ::set-output name=VERSION::$(python -c "import datetime; print(datetime.datetime.now().strftime('%Y.%m.%d'))")
      
    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REPOSITORY: kumar
      run: |
        docker build -t $DOCKER_REPOSITORY:Q1 .
        docker tag $DOCKER_REPOSITORY:Q1 $DOCKER_REPOSITORY:${{ steps.version.outputs.VERSION }}
        docker push $DOCKER_REPOSITORY:Q1
        docker push $DOCKER_REPOSITORY:${{ steps.version.outputs.VERSION }}

