name: Docker Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        # Set version based on your logic
        # Example: Increment PATCH version
        export VERSION=$(git describe --abbrev=0 --tags)
        export NEW_VERSION=$(python -c "version = '${VERSION}'.split('.'); version[2] = str(int(version[2])+1); print('.'.join(version))")
        echo "New version: $NEW_VERSION"
        
        docker build -t tharun123/kumar:latest .
        docker push tharun123/kumar:latest
        docker tag tharun123/kumar:latest tharun123/kumar:${NEW_VERSION}
        
        
        
